### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by paddyroddy**
Generated from here https://bttger.github.io/contributing-gen-web

### CODE REVIEW

**Comment by dstansby** [comment]
I started reading this, and have some pending in-line comments, but got a bit bored since it's very verbose... I worry that others will not bother reading all of this either. I like the intent though, so wonder if there any shorter versions out there?

**Comment by samcunliffe** [comment]
I would rather word it ourselves and pull out the contributing part of README.

Do you want me to take a stab at this?

**Comment by paddyroddy** [comment]
> Do you want me to take a stab at this?

Yes plox

**Comment by samcunliffe** [comment]
☝️  I'll start from scratch.

**Comment by paddyroddy** [comment]
> ☝️ I'll start from scratch.

Can't wait xox

**Pull request closed without merging**
