### PR TITLE
Run pages build on PRs that touch docs.

### PR DESCRIPTION
**Pull request by samcunliffe**
Should help notice bugs like #376 → #377.

Follows from
- #377 

Along the way to solving
- #363

### CODE REVIEW

**Review by matt-graham — APPROVED** [review]
Looks good to me 👍

**Review by paddyroddy — APPROVED** [review]
🫐

**Comment by samcunliffe** [comment]
For ref: you guys are welcome to merge anything of mine that you approve.

**Comment by paddyroddy** [comment]
> For ref: you guys are welcome to merge anything of mine that you approve.

Thank you for permission, but I'm not going to 😁

**Pull request merged**
