### PR TITLE
Native TOML support for `tox`

### LINKED ISSUE #455: Adopt native TOML `tox` support
### Is Your Feature Request Related to a Problem? Please Describe

Following https://github.com/tox-dev/tox/issues/3353 https://github.com/ymyzk/tox-gh-actions/discussions/197, it will at some be possible to have full native TOML support. I tried this for now and couldn't get it to work, so we might need to wait a bit. This would involve removing the lecacy INI format.

### Describe the Solution You'd Like

_No response_

### Describe Alternatives You've Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by paddyroddy**
Fixes #455. In order to do this, have also switched from `tox-gh-actions` to `tox-gh`. Has been tested in https://github.com/astro-informatics/sleplet/pull/420, https://github.com/astro-informatics/sleplet/pull/421.

- [x] Will need to check if templating works correctly

### CODE REVIEW

**Comment by dstansby** [comment]
I would just filter `.pyc` files out of the comparison (like the `.git` folder is) to make it a bit easier

**Comment by paddyroddy** [comment]
> I would just filter `.pyc` files out of the comparison (like the `.git` folder is) to make it a bit easier

Ah, thanks, that bit was annoying me. Guessing it is a difference between `tox-gh` and `tox-gh-actions`.

**Comment by paddyroddy** [comment]
Thanks @dstansby!

**Review by samcunliffe — APPROVED** [review]
This looks great. We should probably add it to our recommendations page? Because `toml`-er is better.

**Comment by paddyroddy** [comment]
> This looks great. We should probably add it to our recommendations page? Because `toml`-er is better.

👍 have raised https://github.com/UCL-ARC/python-tooling/issues/461

**Pull request merged**
