### PR TITLE
Make funder optional

### LINKED ISSUE #290: [TASK]: Make funder option optional
### What needs to be done?

Currently, you are forced to pick a funder, this may not always be appropriate,

### PR DESCRIPTION
**Pull request by dstansby**
Fixes https://github.com/UCL-ARC/python-tooling/issues/290; depends on https://github.com/UCL-ARC/python-tooling/pull/405.

### CODE REVIEW

**Review by samcunliffe — APPROVED** [review]
This also looks great. 🫐 

I appreciated in today's workshop how we don't want to force this on users.

**Comment by samcunliffe** [comment]
Is prettier complaining about the `{% if cookiecutter.funder != '' %}` clause? Because we're using `{% if...` elsewhere in template README.

**Comment by dstansby** [comment]
Might be because without a funder the README was getting two newlines at the end? Lets see if my fix works...

**Comment by paddyroddy** [comment]
So I've had a look and `prettier` currently fails if there's a funder or not.

Without funder - removes trailing line
image

With funder - two different lines removed
image

Let me have a play

**Comment by paddyroddy** [comment]
I've fixed the no funder case

**Comment by paddyroddy** [comment]
This is fixed now @dstansby. Basically, it was just some `jinja2` syntax missing. In general, I've found it best to have things in the following format (note the `-`):

```jinja2
{%- if something %}
some code
{%- endif %}
```

**Comment by dstansby** [comment]
What does the `-` do?

**Review by paddyroddy — APPROVED** [review]
🫐

**Comment by paddyroddy** [comment]
> What does the `-` do?

Just whitespace control https://www.redpill-linpro.com/techblog/2023/07/19/jinja_whitespaces.html

**Pull request merged**
