### PR TITLE
Revert "[pre-commit.ci] pre-commit autoupdate"

### PR DESCRIPTION
**Pull request by paddyroddy**
Reverts UCL-ARC/python-tooling#479

We don't want the alpha version

### CODE REVIEW

**Comment by paddyroddy** [comment]
Another issue is this isn't going to update the template's ones. We don't want this on at all.

**Review by dstansby — DISMISSED** [review]
I think it's good to keep these up to date, so see no reason to revert this. If you want to disable pre-commit.ci auto updating the versions, please could you open a new issue and we can discuss there?

**Comment by paddyroddy** [comment]
@renovatebot will do it in 3 days...

**Comment by samcunliffe** [comment]
🤷 

I'm ok with alphas. But if we decide never to take pre-commit autoupdates and only use @renovate: can we actually disable it in the `ci:` config, please? [It's not immediately clear to me but I guess it's possible](https://pre-commit.ci/#configuration).

**Comment by dstansby** [comment]
I've re-opened https://github.com/UCL-ARC/python-tooling/issues/463 to discuss, so we can make sure discussion is in one place for future reference

**Comment by paddyroddy** [comment]
> I'm ok with alphas. But if we decide never to take pre-commit autoupdates and only use @renovate: can we actually disable it in the `ci:` config, please? [It's not immediately clear to me but I guess it's possible](https://pre-commit.ci/#configuration).

It's not possible https://github.com/pre-commit-ci/issues/issues/83

**Comment by dstansby** [comment]
@paddyroddy could you post the issue you've found on this thread? I think they're spread around several PRs/issues at the moment, and I'm struggling to find them all 😄

**Comment by paddyroddy** [comment]
Also the problem is this doesn't update the template which @renovatebot would

**Review by samcunliffe — APPROVED** [review]
Let's revert this and add the bot back?
- https://github.com/UCL-ARC/python-tooling/issues/463#issuecomment-2451500351

**Pull request merged**
