### PR TITLE
Add all-contributors section to README

### LINKED ISSUE #372: Add https://github.com/all-contributors/all-contributors
### Is Your Feature Request Related to a Problem? Please Describe

No

### Describe the Solution You'd Like

Add the contributing thing to the top level README

### Describe Alternatives You've Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by dstansby**
I'm following the instructions at https://allcontributors.org/docs/en/bot/installation. I think I already installed the GitHub app to this repository, so here's the config needed.

Fixes https://github.com/UCL-ARC/python-tooling/issues/372

### CODE REVIEW

**Comment by dstansby** [comment]
I think we need to merge this PR, and then we can start using the bot commands to add people: https://allcontributors.org/docs/en/bot/usage

**Comment by paddyroddy** [comment]
> I think we need to merge this PR, and then we can start using the bot commands to add people: [allcontributors.org/docs/en/bot/usage](https://allcontributors.org/docs/en/bot/usage)

Yeah, I think that's correct. I was working on this repo during the CW24 hackathon, who introduced it to me https://github.com/reproducibleMATLAB/matlab-project-template.

**Review by matt-graham — APPROVED** [review]
Agree this looks like everything that is needed from the linked installation docs. Possibly may be worth also adding a short section to our `CONTRIBUTING.md` as suggested in the docs - for example something like

```md
## All Contributors

We use [All Contributors](https://allcontributors.org/) to help recognize and 
credit all contributors to the project. The `all-contributors` bot can be used 
[to add new contributors](https://allcontributors.org/docs/en/bot/usage)
by commenting on an issue or pull-request.

```

**Comment by matt-graham** [comment]
🤞 

@all-contributors 
please add @dstansby for ideas, bug, code, content, doc, eventOrganizing, projectManagement, review, test.
please add @paddyroddy for ideas, bug, code, content, doc, eventOrganizing, projectManagement, question, review, talk, test.
please add @samcunliffe for ideas, bug, code, content, doc, eventOrganizing, projectManagement, question, review, talk, test.
please add @matt-graham for bug, code, content, doc, design, eventOrganizing, review, talk, test.
please add @sfmig for bug, code, content, review, test.
please add @p-j-smith for bug, code, content, doc, question, review, test.
please add @ruaridhg for bug, code, content, review.
pleass add @mxochicale for bug, code, content, design, doc, review.
please add @yidilozdemir for doc.
please add @giordano for bug, doc, review.
please add @t-young31 for bug, content, review.
please add @alessandrofelder for bug, content.
please add @adamltyson for content.
please add @willGraham01 for content, review.
please add @nikk-nikaznan for content.
please add @robertvi for doc.
please add @dpshelio for question.
please add @katiebuntic for content.

**Comment by matt-graham** [comment]
Basis for the above is:

Contributing to cookiecutter template ~ code
Contributing to website pages ~ content
Contributing to docs for this repo ~ docs
Raising an issue ~ bug
Reviewing on a PR ~ review
Answering a discussion (or being tagged as answering a question offline) ~ question
Creating one of logo ideas ~ design
Organizing one of docathons or festival workshop ~ eventOrganizing
Presenting at workshop / demo ~ talk

I've also added ideas and projectManagement for @dstansby, @paddyroddy and @samcunliffe on the basis that I think the three of you have been the driving forces behind the project at various stages, but feel free to suggest removing in the associated PRs!

**Comment by matt-graham** [comment]
@all-contributors please add @matt-graham for bug, code, content, doc, design, eventOrganizing, review, talk, test.

**Comment by matt-graham** [comment]
@all-contributors
please add @sfmig for bug, code, content, review, test.
please add @p-j-smith for bug, code, content, doc, question, review, test.
please add @ruaridhg for bug, code, content, review.

**Comment by matt-graham** [comment]
Seems like there might be some form of rate limiting preventing too many requests to the bot being actioned at once, so will split over multiple batches. Sorry for the tagging noise everyone.

**Comment by paddyroddy** [comment]
@all-contributors please add @renovatebot for maintenance

😆

**Comment by paddyroddy** [comment]
@all-contributors can you try again?

**Comment by paddyroddy** [comment]
Lazy.

@all-contributors please add @renovatebot for maintenance

**Comment by matt-graham** [comment]
@all-contributors please add @ruaridhg for bug, code, content, review.

**Comment by matt-graham** [comment]
@all-contributors please add @mxochicale for bug, code, content, design, doc, review.

**Comment by matt-graham** [comment]
@all-contributors please add @yidilozdemir for doc, test.

**Comment by matt-graham** [comment]
@all-contributors please add @giordano for bug, doc, review.

**Comment by matt-graham** [comment]
@all-contributors please add @t-young31 for bug, content, review.

**Comment by matt-graham** [comment]
@all-contributors please add @alessandrofelder for bug, content.

**Comment by matt-graham** [comment]
@all-contributors please add @adamltyson for content.

**Comment by matt-graham** [comment]
@all-contributors please add @willGraham01 for content, review.

**Comment by matt-graham** [comment]
@all-contributors please add @nikk-nikaznan for content.

**Comment by matt-graham** [comment]
@all-contributors please add @katiebuntic for content.

**Comment by matt-graham** [comment]
@all-contributors please add @robertvi for doc.

**Comment by matt-graham** [comment]
@all-contributors please add @dpshelio for code, question.

**Pull request merged**
