### PR TITLE
Update to 3.13, drop 3.10

### PR DESCRIPTION
**Pull request by samcunliffe**

### CODE REVIEW

**Comment by samcunliffe** [comment]
Think we may have to wait for 
https://github.com/actions/python-versions/pull/312

(cc. @Saransh-cpp)

**Review by paddyroddy — DISMISSED** [review]
Can you look at `tutorial.md` where it mentions `3.12`? We should either remove that (my vote) or update to `3.13`.

**Comment by samcunliffe** [comment]
> Can you look at `tutorial.md` where it mentions `3.12`? We should either remove that (my vote) or update to `3.13`.

Reached by @dstansby in #459 🚀

**Comment by samcunliffe** [comment]
Not related to this PR, but for the repo `main` ruleset, should we require 3.13 to pass also?

**Review by dstansby — APPROVED** [review]

**Comment by paddyroddy** [comment]
> Not related to this PR, but for the repo `main` ruleset, should we require 3.13 to pass also?

Yes, I had it ticked on, but then it was blocking #459. Will turn on now, if not already on. I had turned off the 3.10 ones.

**Pull request merged**
