### PR TITLE
Replace `black` with `ruff-format`

### LINKED ISSUE #204: https://astral.sh/blog/the-ruff-formatter
That is all

### PR DESCRIPTION
**Pull request by paddyroddy**
Fixes #204

### CODE REVIEW

**Review by samcunliffe — CHANGES_REQUESTED** [review]
If we're doing this, we should add `ruff-format` to the linters page as 🟢 and demote `black` to 🟠.

- [x] update pages.

**Comment by paddyroddy** [comment]
> If we're doing this, we should add `ruff-format` to the linters page as 🟢 and demote `black` to 🟠.

I thought about this, but its a bit weird as its still `ruff`. Like its the same application.

**Comment by samcunliffe** [comment]
> I thought about this, but its a bit weird as its still ruff. Like its the same application.

Weird slightly: but now very clear IMHO. And clarity trumps weirdness.

**Review by samcunliffe — APPROVED** [review]
🍉

**Pull request merged**
