### PR TITLE
Adding logo to README header

### PR DESCRIPTION
**Pull request by matt-graham**
Follow on from #277 - adds logo to README file. Hopefully link checker will now not fail as logo file now on `main` 🤞.

### CODE REVIEW

**Review by paddyroddy — APPROVED** [review]
🤞

**Comment by paddyroddy** [comment]
@dstansby title case was about to be fixed!

**Comment by dstansby** [comment]
> @dstansby title case was about to be fixed!

Why did you approve then 😄

**Comment by paddyroddy** [comment]
> Why did you approve then 😄

I didn't spot it until afterwards

**Pull request merged**
