### PR TITLE
Minor improvements to dev tools

### PR DESCRIPTION
**Pull request by dstansby**
Just very minor sentence/language improvements here.

### CODE REVIEW

**Review by samcunliffe — APPROVED** [review]
This makes #265 stale again.

But! It's much better. So in it goes.

**Comment by paddyroddy** [comment]
> This makes #265 stale again.

If the author isn't responding, should we just close it?

**Comment by dstansby** [comment]
I think worth keeping open as a reminder that it's worth merging, even if that means someone else picking it up and finishing the PR?

**Comment by samcunliffe** [comment]
> I think worth keeping open as a reminder that it's worth merging, even if that means someone else picking it up and finishing the PR?

In general: yes. But #265 is slowly losing relevance as more and more of it's sub-issues get addressed elsewhere.

**Pull request merged**
