### PR TITLE
Sphinx docs

### LINKED ISSUE #16: Add documentation
A really lazy way: paddyroddy/python-template#9 (+ paddyroddy/python-template#10 + paddyroddy/python-template#11) as I'm an idiot) which allows you to just use `github-pages` deploying from a `gh-pages` branch with these settings
image

A better example that I just did looks like: https://astro-informatics.github.io/sleplet/

### PR DESCRIPTION
**Pull request by sfmig**
- [x] Basic sphinx docs directory layout with themes
- [x] Add Sphinx docs to cookiecutter template folder
    - the [NIU cookiecutter](https://github.com/neuroinformatics-unit/python-cookiecutter/blob/main/%7B%7Bcookiecutter.package_name%7D%7D/docs/source/index.rst) is a nice example
- [x] Add extensions to conf.py
- [x] Hardcoded copyright number (see #191 )
- [x] Automatic documentation generation from code
- [ ] Doc generation via workflow/PR
- [ ] Add instructions

Closes #16

### CODE REVIEW

**Comment by paddyroddy** [comment]
We should add CI for users too to just make the docs

**Comment by paddyroddy** [comment]
Have modified to incorporate the changes in  #197 (tests passing)

**Comment by samcunliffe** [comment]
Is this still WIP?

**Comment by sfmig** [comment]
💀

**Pull request closed without merging**
