### PR TITLE
Update and rename .renovaterc.json to .renovaterc.json5

### PR DESCRIPTION
**Pull request by paddyroddy**

### CODE REVIEW

**Review by dstansby — DISMISSED** [review]
Why/what's the context for this?

Marking as request changes since tests are all failing.

**Comment by paddyroddy** [comment]
> Why/what's the context for this?

Just consistent with what I've done elsewhere. Nicer syntax IMO.

> Marking as request changes since tests are all failing.

This is obviously completely unrelated. Have no idea why...

**Comment by paddyroddy** [comment]
@dstansby they are now passing 🤷

**Review by samcunliffe — APPROVED** [review]

**Comment by samcunliffe** [comment]
🫐 Expliciter is betterer.

**Pull request merged**
