### PR TITLE
Delete IDE table

### LINKED ISSUE #256: Delete the IDEs table.

### PR DESCRIPTION
**Pull request by paddyroddy**
Fixes #256

### CODE REVIEW

**Review by samcunliffe — APPROVED** [review]

**Comment by paddyroddy** [comment]
https://libraries.io/pypi/cookiecutter being flaky, merging

**Comment by samcunliffe** [comment]
That's the second time the linkchecker has timed out (?)
But it's a different URL to the --ironically-- vscode link that was problematic last time IIRC.

**Comment by paddyroddy** [comment]
Hmm... But I tried https://libraries.io/ and it genuinely took a while to load

**Comment by samcunliffe** [comment]
¯\\\_(ツ)\_/¯ 

Passed on main.

**Pull request merged**
